# Generated by Django 3.0.6 on 2020-05-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('category', models.TextField(blank=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
